/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SolutionService } from "../solution.service";
import { SolutionCreateInput } from "./SolutionCreateInput";
import { Solution } from "./Solution";
import { SolutionFindManyArgs } from "./SolutionFindManyArgs";
import { SolutionWhereUniqueInput } from "./SolutionWhereUniqueInput";
import { SolutionUpdateInput } from "./SolutionUpdateInput";

export class SolutionControllerBase {
  constructor(protected readonly service: SolutionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Solution })
  async createSolution(
    @common.Body() data: SolutionCreateInput
  ): Promise<Solution> {
    return await this.service.createSolution({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Solution] })
  @ApiNestedQuery(SolutionFindManyArgs)
  async solutions(@common.Req() request: Request): Promise<Solution[]> {
    const args = plainToClass(SolutionFindManyArgs, request.query);
    return this.service.solutions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Solution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async solution(
    @common.Param() params: SolutionWhereUniqueInput
  ): Promise<Solution | null> {
    const result = await this.service.solution({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Solution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSolution(
    @common.Param() params: SolutionWhereUniqueInput,
    @common.Body() data: SolutionUpdateInput
  ): Promise<Solution | null> {
    try {
      return await this.service.updateSolution({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          content: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Solution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSolution(
    @common.Param() params: SolutionWhereUniqueInput
  ): Promise<Solution | null> {
    try {
      return await this.service.deleteSolution({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          content: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
