/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Problem } from "./Problem";
import { ProblemCountArgs } from "./ProblemCountArgs";
import { ProblemFindManyArgs } from "./ProblemFindManyArgs";
import { ProblemFindUniqueArgs } from "./ProblemFindUniqueArgs";
import { CreateProblemArgs } from "./CreateProblemArgs";
import { UpdateProblemArgs } from "./UpdateProblemArgs";
import { DeleteProblemArgs } from "./DeleteProblemArgs";
import { ProblemService } from "../problem.service";
@graphql.Resolver(() => Problem)
export class ProblemResolverBase {
  constructor(protected readonly service: ProblemService) {}

  async _problemsMeta(
    @graphql.Args() args: ProblemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Problem])
  async problems(
    @graphql.Args() args: ProblemFindManyArgs
  ): Promise<Problem[]> {
    return this.service.problems(args);
  }

  @graphql.Query(() => Problem, { nullable: true })
  async problem(
    @graphql.Args() args: ProblemFindUniqueArgs
  ): Promise<Problem | null> {
    const result = await this.service.problem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Problem)
  async createProblem(
    @graphql.Args() args: CreateProblemArgs
  ): Promise<Problem> {
    return await this.service.createProblem({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Problem)
  async updateProblem(
    @graphql.Args() args: UpdateProblemArgs
  ): Promise<Problem | null> {
    try {
      return await this.service.updateProblem({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Problem)
  async deleteProblem(
    @graphql.Args() args: DeleteProblemArgs
  ): Promise<Problem | null> {
    try {
      return await this.service.deleteProblem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
